# Cleaning the Size of collected Dataset

Currently, known size that need to clean:
```
## This is for size:
map = {
    "mkt77008719": ["0.2 oz", "8 g"] # on the website, it said "2 ct" meaning 2 products, each product is 4 g. Therefore, the total is "4 g" or "0.4 o"
    }
```

## Setup

In [95]:
import pandas as pd
import numpy as np
# import csv

In [96]:
import re

## Size Map

In [97]:
## This is for size:
map = {
    "mkt77008719": ["0.2 oz", "8 g"] # on the website, it said "2 ct" meaning 2 products, each product is 4 g. Therefore, the total is "4 g" or "0.4 o"
    }

In [ ]:
# SIZE_MAP_METRIC = {
#     "24 g": ["Glimmer Super Balm"],
#     "22 g": ["Marble Cream Blush Stick"],
#     "21 g": ["Ultimate Blush Palette"],
#     "16.8 g": ["Blushed Duo"],
#     "12 g": ["Blursh Pod Domed Blusher"],
#     "10 g": ["MegaGlo Blushlighter"],
#     "9.5 g": ["VividLuxe Crème Blush Stick"],
#     "9 g": ["DreamStick Cream Blush"],
#     "8.5 g": ["Cream Stick Blush with Brush Applicator", "Blush Crush Liquid Blush"],
#     "8.4 g": ["Effervescence Extra Dimension Face Compact", ],
#     "8 g": ["Juice Stick Dewy Gel-Cream Blush", "Juice Stick Dewy Gel Blush", "Juice Stick Dewy Sheer Gel Blush"],
#     "7.7 g": ["Blushed Liquid Blushlighter"],
#     "7.5 g": ["Glow Time Blush Stick", "Teint Idole Shape Stick Creamy Blush Stick"],
#     "6 g": [
#         "Blushed Cream Blush",
#         "Matte Blush",
#         "Megaglo Makeup Stick",
#         "I'm Blushing 2-in-1 Cheek and Lip Tint",
#         "Heart Pressed Powder Blush",
#         "Bouncy Pudding Lip & Cheek Tint",
#         "Backstage Rosy Glow Stick Radiance and pH-Activated Color Blush Stick",
#     ],
#     "5.5 g": [
#         "Blusher Reloaded",
#         "Jelly Blush Stick Lip & Cheek Stain",
#         "Baby Got Blush",
#         "Bouncy Blur Blush",
#     ],
#     "5 g": [
#         "2-in-1 Mosaic Blush & Bronzer Powder",
#         "Liquid Blush - 2-in-1 Lip & Cheek Tint",
#         "Strawberry Rococo Series Embossed Blush",
#     ],
#     "4.5 g": ["Blush-Mallow Soft Blusher", "Skin Silk Marble Blush Stick"],
#     "4.3 g": ["Mini VividLuxe Crème Blush Stick"],
#     "4.25 g": ["Convertible Color Lip & Cheek Cream Blush"],
#     "4 g": ["Color Source Buildable Blush", "Re-tint Blurring Cream Blush"],
#     "3.2 g": ["PurePressed Blush"],
#     "3 g": ["Magic Touch Cream Blush & Lip Trio", "Just Kissed Lip and Cheek Stain", "Pressed Mineral Blush"],
#     "2.5 g": ["Baked Blush"],
#     "15 ml": ["Hot Shot Blush Drops", "Tinted Moisturizer Cream Blush"],
#     "10.3 ml": ["Unreal Liquid Blush"],
#     "10 ml": [
#         "Futurist Blushmaker Dewy Cheek Tint Liquid Blush",
#         "Superdewy Liquid Blush Burst",
#         "Juicy Tubes Cheeks Jelly Blush Tint",
#     ],
#     "9.5 ml": ["Glimmer Blush Drops"],
#     "8.5 ml": ["Skin Idôle Juicy Liquid Blush"],
#     "8 ml": ["Maneater Satin Blush Cheek Plump", 
#              "Simpsons Collab Saucy Sisters' Fat Cheeks Juicy Liquid Blush - Snarky Scarlet",
#              "Simpsons Collab Saucy Sisters' Fat Cheeks Juicy Liquid Blush - Lavender Sass"],
#     "7.8 g": ["Macaron Blush & Glow Duo"],
#     "6 ml": ["Play Daze Airy Liquid Blush", "Play Daze Airy Soft Matte Liquid Blush"],
#     "3.9 ml": ["Jelly Tint - 2-in-1 Lip & Cheek Tint Stain"],
#     "3.5 ml": ["Blush Rush Liquid Blush"],
    
# }

# # drop product_id == "mkt77005996", no longer exist

In [146]:
SIZE_MAP_OZ = {
    '0.8 oz': ['Glimmer Super Balm', 'Marble Cream Blush Stick']
    , '0.7 oz': ['Ultimate Blush Palette'], '0.6 oz': ['Blushed Duo']
    , '0.4 oz': ['Blursh Pod Domed Blusher', 'MegaGlo Blushlighter']
    , '0.3 oz': ['VividLuxe Crème Blush Stick', 'DreamStick Cream Blush', 'Cream Stick Blush with Brush Applicator', 'Blush Crush Liquid Blush', 'Effervescence Extra Dimension Face Compact', 'Juice Stick Dewy Gel-Cream Blush', 'Juice Stick Dewy Gel Blush', 'Juice Stick Dewy Sheer Gel Blush', 'Blushed Liquid Blushlighter', 'Glow Time Blush Stick', 'Teint Idole Shape Stick Creamy Blush Stick', 'Unreal Liquid Blush', 'Futurist Blushmaker Dewy Cheek Tint Liquid Blush', 'Superdewy Liquid Blush Burst', 'Juicy Tubes Cheeks Jelly Blush Tint', 'Glimmer Blush Drops', 'Skin Idôle Juicy Liquid Blush', 'Maneater Satin Blush Cheek Plump', "Simpsons Collab Saucy Sisters' Fat Cheeks Juicy Liquid Blush - Snarky Scarlet", "Simpsons Collab Saucy Sisters' Fat Cheeks Juicy Liquid Blush - Lavender Sass", 'Macaron Blush & Glow Duo']
    , '0.2 oz': ['Blushed Cream Blush', 'Matte Blush', 'Megaglo Makeup Stick', "I'm Blushing 2-in-1 Cheek and Lip Tint", 'Heart Pressed Powder Blush', 'Bouncy Pudding Lip & Cheek Tint', 'Backstage Rosy Glow Stick Radiance and pH-Activated Color Blush Stick', 'Blusher Reloaded', 'Jelly Blush Stick Lip & Cheek Stain', 'Baby Got Blush', 'Bouncy Blur Blush', '2-in-1 Mosaic Blush & Bronzer Powder', 'Liquid Blush - 2-in-1 Lip & Cheek Tint', 'Strawberry Rococo Series Embossed Blush', 'Blush-Mallow Soft Blusher', 'Skin Silk Marble Blush Stick', 'Mini VividLuxe Crème Blush Stick', 'Play Daze Airy Liquid Blush', 'Play Daze Airy Soft Matte Liquid Blush']
    , '0.1 oz': ['Convertible Color Lip & Cheek Cream Blush', 'Color Source Buildable Blush', 'Re-tint Blurring Cream Blush', 'PurePressed Blush', 'Magic Touch Cream Blush & Lip Trio', 'Just Kissed Lip and Cheek Stain', 'Pressed Mineral Blush', 'Baked Blush', 'Jelly Tint - 2-in-1 Lip & Cheek Tint Stain', 'Blush Rush Liquid Blush']
    , '0.5 oz': ['Hot Shot Blush Drops', 'Tinted Moisturizer Cream Blush']
    }

In [100]:
# DUPLICATED_UNIT_PATTERN = re.compile(
#     r"\b(oz|g|ml|ct)\.?\s+\1\.?\s*$",
#     flags=re.IGNORECASE,
# )

# pattern = r'(\d+\.?\d*)\s*(.+)'
# # pattern = r'(\d+\.?\d*)\s*([a-zA-Z]+\.?)'

## Load Dataset

In [101]:
# with open(r"..\data\processed_data\test\blushes\_export_summary.csv", mode="r", newline="", encoding="utf-8") as filename:
#     reader = csv.reader(filename)

#     list = ["palettes_no_swatch_image", "palettes_with_swatch_image", "multi_color_swatch_image", "single_color_no_swatch_image", "single_color_swatch_image", "set_blush"]
#     i = 0
#     for row in reader:
#         # print(row[3])
#         print(f"Path: {list[i]} = pd.read_csv(r'{row[3]}', encoding='utf-8-sig')")

#         i =i+1 
#         if i >= len(list):
#             break

In [102]:
single_color_swatch_image = pd.read_csv(r'../data/processed_data/test/blushes\single_color_swatch_image.csv', encoding='utf-8-sig')
single_color_swatch_image.info()

<class 'pandas.DataFrame'>
RangeIndex: 1365 entries, 0 to 1364
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1365 non-null   str
 1   sku_id               1365 non-null   int64
 2   variant_type         1365 non-null   str
 3   variant_name         1365 non-null   str
 4   variant_description  1027 non-null   str
 5   variant_url          1365 non-null   str
 6   list_price           1365 non-null   float64
 7   sale_price           37 non-null     float64
 8   size_text            1178 non-null   str
 9   availability         1365 non-null   str
 10  swatch_image_url     1365 non-null   str
 11  variant_image_url    1365 non-null   str
 12  ingredient_set_id    1335 non-null   str
dtypes: float64(2), int64(1), str(10)
memory usage: 138.8 KB

In [103]:
products = pd.read_csv(r"..\data\raw\blush\20260724T001508Z\products.csv", encoding="utf-8-sig")
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 346 entries, 0 to 345
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    346 non-null    str
 1   brand         346 non-null    str
 2   product_name  346 non-null    str
 3   product_url   346 non-null    str
 4   rating        307 non-null    float64
 5   review_count  307 non-null    float64
dtypes: float64(2), str(4)
memory usage: 16.3 KB

## EDA

In [104]:
def check_missing(df, column):
    missing_mask = (
        df[column].isna() # null value 
        | df[column].astype("string").str.strip().eq("") # OR has "" as str
    )
    missing_count = missing_mask.sum()
    missing_rows = df.loc[missing_mask]
    missing_unique = missing_rows['product_id'].drop_duplicates()
    
    print(f"Number of Unique product_id: {len(df['product_id'].unique())}")
    print(f"Number Rows of Missing Value in '{column}': {missing_count}")
    print(f"Number of missing value of '{column}' per unique 'product_id': {len(missing_unique)}")

    return missing_rows

In [105]:
check_missing(single_color_swatch_image, 'size_text')

Number of Unique product_id: 234
Number Rows of Missing Value in 'size_text': 187
Number of missing value of 'size_text' per unique 'product_id': 38

,product_id,sku_id,variant_type,variant_name,variant_description,variant_url,list_price,sale_price,size_text,availability,swatch_image_url,variant_image_url,ingredient_set_id
25,pimprod2025280,2583745,color,Vol 1,deep earthy tones,https://www.ulta.com/p/blushed-duo-pimprod2025...,20.0,NaN,NaN,InStock,https://media.ultainc.com/i/ulta/2583745_sw?im...,https://media.ultainc.com/i/ulta/2583745?w=500...,ae918d542b3775b7b30db627816f15c76d2bae5f25a1f9...
26,pimprod2025280,2583746,color,Vol 2,soft pops of bright color,https://www.ulta.com/p/blushed-duo-pimprod2025...,20.0,NaN,NaN,InStock,https://media.ultainc.com/i/ulta/2583746_sw?im...,https://media.ultainc.com/i/ulta/2583746?w=500...,6e477035993a69b34b4b4b0187011ac2789514b901a277...
27,pimprod2025280,2637222,color,Vol 3,NaN,https://www.ulta.com/p/blushed-duo-pimprod2025...,20.0,NaN,NaN,InStock,https://media.ultainc.com/i/ulta/2637222_sw?im...,https://media.ultainc.com/i/ulta/2637222?w=500...,NaN
240,pimprod2056002,2649449,color,Toasted Coconut,rosy beige,https://www.ulta.com/p/macaron-blush-glow-duo-...,38.0,NaN,NaN,InStock,https://media.ultainc.com/i/ulta/2649449_sw?im...,https://media.ultainc.com/i/ulta/2649449?w=500...,47239d2f192b6d0019d2484102b1afce5f80135be99c01...
241,pimprod2056002,2649450,color,Pink Champagne,pink,https://www.ulta.com/p/macaron-blush-glow-duo-...,38.0,NaN,NaN,InStock,https://media.ultainc.com/i/ulta/2649450_sw?im...,https://media.ultainc.com/i/ulta/2649450?w=500...,31708b33bf705a92ab8b0c7471f491ead68b8722ff8e4d...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1360,mkt77009883,77015425,color,Tiramisu,rich cinnamon,https://www.ulta.com/p/vividluxe-creme-blush-s...,48.0,NaN,NaN,InStock,https://media.ultainc.com/i/ulta/77015425_sw?i...,https://media.ultainc.com/i/ulta/77015425?w=50...,983b02eae1bab7dc1a1b43504cda4e096f8ec8b0928fd5...
1361,mkt77009884,77015422,color,Sugar Plum,soft rosy coral with shimmer,https://www.ulta.com/p/pressed-mineral-blush-m...,30.0,NaN,NaN,InStock,https://media.ultainc.com/i/ulta/77015422_sw?i...,https://media.ultainc.com/i/ulta/77015422?w=50...,0c9333186d08b09ef8d804ea034f67916b8c2a8f8a2ba1...
1362,mkt77009884,77015419,color,Blossom,soft matte pink,https://www.ulta.com/p/pressed-mineral-blush-m...,30.0,NaN,NaN,InStock,https://media.ultainc.com/i/ulta/77015419_sw?i...,https://media.ultainc.com/i/ulta/77015419?w=50...,0c9333186d08b09ef8d804ea034f67916b8c2a8f8a2ba1...
1363,mkt77009884,77015427,color,Nectar,soft peach,https://www.ulta.com/p/pressed-mineral-blush-m...,30.0,NaN,NaN,InStock,https://media.ultainc.com/i/ulta/77015427_sw?i...,https://media.ultainc.com/i/ulta/77015427?w=50...,0c9333186d08b09ef8d804ea034f67916b8c2a8f8a2ba1...
1364,mkt77009884,77015406,color,Tangier,shimmering coral,https://www.ulta.com/p/pressed-mineral-blush-m...,30.0,NaN,NaN,InStock,https://media.ultainc.com/i/ulta/77015406_sw?i...,https://media.ultainc.com/i/ulta/77015406?w=50...,0c9333186d08b09ef8d804ea034f67916b8c2a8f8a2ba1...

In [106]:
(
    single_color_swatch_image["size_text"]
    .isna()
    .groupby(single_color_swatch_image["product_id"], dropna=False)
    .sum()
    .reset_index(name="missing_product_size_count")
)

             product_id  missing_product_size_count
0               VP10730                           0
1               VP12620                           0
2           mkt77000420                           0
3           mkt77000967                           0
4           mkt77001349                           0
..                  ...                         ...
229  xlsImpprod16281007                           0
230  xlsImpprod16731045                           0
231  xlsImpprod18001081                           0
232   xlsImpprod3650106                           0
233    xlsImpprod820350                           0

[234 rows x 2 columns]

In [107]:
products[products['product_name'].apply(lambda x: '\u00a0' in str(x))]

,product_id,brand,product_name,product_url,rating,review_count
84,pimprod2059619,Clinique,Daily Calm Lip + Cheek Color,https://www.ulta.com/p/daily-calmlip-cheek-col...,4.3,415.0
121,pimprod2055435,Estée Lauder,Futurist Blushmaker Dewy Cheek Tint Liquid Blush,https://www.ulta.com/p/futurist-blushmaker-dew...,4.7,481.0

In [108]:
def parse_size(row):
    match = re.fullmatch(
        r"\s*(\d*\.?\d+)\s*(.*?)\s*",
        str(row["size_text"]),
    )

    if not match:
        return row["sku_id"], None, None

    value = float(match.group(1))
    unit = match.group(2).strip()

    return row["sku_id"], value, unit


parsed_sizes = single_color_swatch_image.apply(
    parse_size,
    axis=1,
    result_type="expand",
)

parsed_sizes.columns = ["sku_id", "value", "unit"]

In [109]:
parsed_sizes.unit.value_counts()

unit
oz        1144
oz. oz       8
ct           3
Name: count, dtype: int64

In [162]:
def parse_size(size_str):
    """
    Parse size strings like "2.5 ml" into (value, unit, status)
    
    Returns:
        tuple: (float_value, unit_string, status_string)
        - status: 'ok', 'missing', 'no_match', 'multiple_units'
    """
    # Handle missing/null values
    if pd.isna(size_str) or not isinstance(size_str, str):
        return None, None, 'missing'
    
    size_str = size_str.strip()
    pattern = r'(\d+\.?\d*)\s*([a-zA-Z]+\.?)'
    
    # Find ALL matches to detect errors
    matches = re.findall(pattern, size_str)
    
    if len(matches) == 0:
        # Pattern didn't match at all
        return None, None, 'no_match'
    elif len(matches) == 1:
        # Perfect: exactly one value-unit pair
        value, unit = matches[0]
        return float(value), unit.rstrip('.'), 'ok'
    else:
        # ERROR: multiple value-unit pairs found (like "0.17 oz. oz")
        value, unit = matches[0]
        return float(value), unit.rstrip('.'), 'multiple_units'

## Cleaning

### Drop Columns and Rows

In [111]:
single_color_swatch_image.drop(columns=['variant_type', 'availability'], inplace = True)
single_color_swatch_image.info()

<class 'pandas.DataFrame'>
RangeIndex: 1365 entries, 0 to 1364
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1365 non-null   str
 1   sku_id               1365 non-null   int64
 2   variant_name         1365 non-null   str
 3   variant_description  1027 non-null   str
 4   variant_url          1365 non-null   str
 5   list_price           1365 non-null   float64
 6   sale_price           37 non-null     float64
 7   size_text            1178 non-null   str
 8   swatch_image_url     1365 non-null   str
 9   variant_image_url    1365 non-null   str
 10  ingredient_set_id    1335 non-null   str
dtypes: float64(2), int64(1), str(8)
memory usage: 117.4 KB

In [112]:
single_color_swatch_image.columns

Index(['product_id', 'sku_id', 'variant_name', 'variant_description',
       'variant_url', 'list_price', 'sale_price', 'size_text',
       'swatch_image_url', 'variant_image_url', 'ingredient_set_id'],
      dtype='str')

In [113]:
products['product_name'] = products['product_name'].str.replace('\u00a0', ' ', regex=False) ## fixing non-breaking space

In [114]:
single_color_swatch_image = single_color_swatch_image.query('product_id != "mkt77005996"') # Drop since it's no longer exist

### Incorrect `size_text`

In [115]:
## Identify the errors 

errors = single_color_swatch_image['size_text'].str.contains('Color:', na=False)

single_color_swatch_image[errors]

,product_id,sku_id,variant_name,variant_description,variant_url,list_price,sale_price,size_text,swatch_image_url,variant_image_url,ingredient_set_id
55,pimprod2044741,2621261,Orgasm - 777,NaN,https://www.ulta.com/p/blush-pimprod2044741?sk...,36.00,NaN,Color: Orgasm - 777,https://media.ultainc.com/i/ulta/2621261_sw?im...,https://media.ultainc.com/i/ulta/2621261?w=500...,97ab50b76cf4072a87867394ad1c97338c8570d2fab1bf...
119,pimprod2050543,2634992,BURST,NaN,https://www.ulta.com/p/cooling-water-jelly-tin...,26.00,NaN,Color: BURST,https://media.ultainc.com/i/ulta/2634992_sw?im...,https://media.ultainc.com/i/ulta/2634992?w=500...,c9794908c11f2bae5f940bcc7434308714301d0d60a6e8...
175,xlsImpprod15921186,2519160,Gentle,NaN,https://www.ulta.com/p/mineralize-powder-blush...,34.00,NaN,Color: Gentle,https://media.ultainc.com/i/ulta/2519160_sw?im...,https://media.ultainc.com/i/ulta/2519160?w=500...,ef4079e0c26a98fda00ef8b62b4f512a8a268b84062ba2...
294,pimprod2049596,2632824,Call My Blush,NaN,https://www.ulta.com/p/gen-nude-powder-blush-p...,29.00,NaN,Color: Call My Blush,https://media.ultainc.com/i/ulta/2632824_sw?im...,https://media.ultainc.com/i/ulta/2632824?w=500...,61990c11a542175f179f5712e5d6e4d4d75630dce7e841...
322,pimprod2043819,2620380,Rose-tinted,NaN,https://www.ulta.com/p/value-size-liquid-lip-b...,36.00,NaN,Color: Rose-tinted,https://media.ultainc.com/i/ulta/2620380_sw?im...,https://media.ultainc.com/i/ulta/2620380?w=500...,eefb414518ddae8d5537f7e5e8030b7e885271bd85a611...
556,pimprod2049564,2633753,02 ROSE BRONZE,NaN,https://www.ulta.com/p/joues-contraste-powder-...,56.00,NaN,Color: 02 ROSE BRONZE,https://media.ultainc.com/i/ulta/2633753_sw?im...,https://media.ultainc.com/i/ulta/2633753?w=500...,7604bdbebecf054f4b7d86ab0a50971d5db22a9a17716b...
1025,pimprod2046332,2624307,Watermelon,NaN,https://www.ulta.com/p/twist-tint-color-shifti...,1.20,NaN,Color: Watermelon (customized color shifting t...,https://media.ultainc.com/i/ulta/2624307_sw?im...,https://media.ultainc.com/i/ulta/2624307?w=500...,be4b44b8bca4adda2fcbe919d2ab65a4ef69e182c99e4f...
1117,pimprod2032200,2596240,Cotton Candy,NaN,https://www.ulta.com/p/purepressed-blush-pimpr...,36.00,NaN,Color: Cotton Candy,https://media.ultainc.com/i/ulta/2596240_sw?im...,https://media.ultainc.com/i/ulta/2596240?w=500...,4c4acec368472cc90579ba833f9f83d963616e4edd8bce...
1120,pimprod2057923,2651574,Lavender Sass,NaN,https://www.ulta.com/p/simpsons-collab-saucy-s...,10.00,NaN,Color: Lavender Sass (lilac pink),https://media.ultainc.com/i/ulta/2651574_sw?im...,https://media.ultainc.com/i/ulta/2651574?w=500...,12341020398f944b1c13b1c7e7d0a94068aa52c421095b...
1126,pimprod2056852,2651496,ph pink,NaN,https://www.ulta.com/p/ph-cheeky-glaze-liquid-...,20.00,NaN,Color: ph pink,https://media.ultainc.com/i/ulta/2651496_sw?im...,https://media.ultainc.com/i/ulta/2651496?w=500...,8c5d43785fd52161163ffce5304f2948d6c0f1227229fc...
1136,pimprod2057925,2651573,Snarky Scarlet,NaN,https://www.ulta.com/p/simpsons-collab-saucy-s...,10.00,NaN,Color: Snarky Scarlet (ruby red),https://media.ultainc.com/i/ulta/2651573_sw?im...,https://media.ultainc.com/i/ulta/2651573?w=500...,e770af0b843f8ef9f2584ba17567ca73266957ef56a338...
1206,pimprod2056483,2652509,4ever Yours,NaN,https://www.ulta.com/p/heart-pressed-powder-bl...,12.00,NaN,Color: 4ever Yours (warm coral red),https://media.ultainc.com/i/ulta/2652509_sw?im...,https://media.ultainc.com/i/ulta/2652509?w=500...,e82761ee8f7591eee1e477abfe99a928e3c856890b4fb5...
1215,pimprod2052046,2641714,Rose Dew,NaN,https://www.ulta.com/p/rose-glow-y-powder-pimp...,18.00,NaN,Color: Rose Dew,https://media.ultainc.com/i/ulta/2641714_sw?im...,https://media.ultainc.com/i/ulta/2641714?w=500...,e16970e4ca9fc5af9f2b1838166d237275b45e8a58c8e8...
1223,pimprod2013408,2559287,Flash Me,NaN,https://www.ulta.com/p/megaglo-blushlighter-pi...,7.49,NaN,Color: Flash Me,https://media.ultainc.com/i/ulta/2559287_sw?im...,https://media.ultainc.com/i/ulta/2559287?w=500...,a39e077a8b8850dd3a96bf36c9c7b6ef3893b1216b82f1...
1224,pimprod2045569,2623457,Mimosa,NaN,https://www.ulta.com/p/cream-powder-blurring-b...,29.00,NaN,Color: Mimosa (vibrant peachy coral),https://media.ultainc.com/i/ulta/2623457_sw?im...,https://media.ultainc.com/i/ulta/2623457?w=500...,92b3bfa196c43d9fefd88f8686fdd0aaa0614f217b35e2...
1225,xlsImpprod16731045,2518207,Floral Majority,NaN,https://www.ulta.com/p/megaglo-makeup-stick-bl...,4.49,NaN,Color: Floral Majority,https://media.ultainc.com/i/ulta/2518207_sw?im...,https://media.ultainc.com/i/ulta/2518207?w=500...,6fae5e36952f7c3d102f17edfe5ce52ea676c1476b9086...
1232,pimprod2047580,2629266,Canela,NaN,https://www.ulta.com/p/cheek-kiss-liquid-blush...,12.99,NaN,Color: Canela (cinnamon),https://media.ultainc.com/i/ulta/2629266_sw?im...,https://media.ultainc.com/i/ulta/2629266?w=500...,964f1b20fa64e67d7c8d3e52a99f3bf889706fb3f119f4...
1233,pimprod2045404,2625731,Rosie Pink,NaN,https://www.ulta.com/p/bright-light-blush-drop...,13.00,NaN,Color: Rosie Pink,https://media.ultainc.com/i/ulta/2625731_sw?im...,https://media.ultainc.com/i/ulta/2625731?w=500...,1c7ac6a9bd6e34bea694b6c8b9bc1a5d14001b385304f9...
1234,pimprod2024993,2583417,You Got Me Blushing,NaN,https://www.ulta.com/p/superdewy-liquid-blush-...,7.00,NaN,Color: You Got Me Blushing (muted rose),https://media.ultainc.com/i/ulta/2583417_sw?im...,https://media.ultainc.com/i/ulta/2583417?w=500...,ccc49a78992c09d8c3a6fb34fb87b74f8aa254c12c7dfc...
1235,pimprod2030849,2592098,Grace,NaN,https://www.ulta.com/p/soft-matte-cream-blush-...,7.00,NaN,Color: Grace,https://media.ultainc.com/i/ulta/2592098_sw?im...,https://media.ultainc.com/i/ulta/2592098?w=500...,d6e0048280154a985cec63eb2aebb80e5c22a7407a17bc...
1236,pimprod2027378,2583892,Rosy,NaN,https://www.ulta.com/p/sheer-cheek-gel-pimprod...,15.00,NaN,Color: Rosy,https://media.ultainc.com/i/ulta/2583892_sw?im...,https://media.ultainc.com/i/ulta/2583892?w=500...,4880e46cdfab383f4d508305df3e80c33af64135803c44...
1237,pimprod2049311,2633533,Orange Crush,NaN,https://www.ulta.com/p/beam-bright-blush-pimpr...,11.00,NaN,Color: Orange Crush (vibrant orange blush with...,https://media.ultainc.com/i/ulta/2633533_sw?im...,https://media.ultainc.com/i/ulta/2633533?w=500...,81503a495efd105be8696c14a9e6cb5f79ab8fcfcbf249...
1244,pimprod2038007,2606193,Bloom,NaN,https://www.ulta.com/p/puff-paint-liquid-blush...,24.00,NaN,Color: Bloom (true cherry),https://media.ultainc.com/i/ulta/2606193_sw?im...,https://media.ultainc.com/i/ulta/2606193?w=500...,3a30c638eef6ebcdd769e3f6542de3c1b07ee8187322d1...

In [116]:
## replace

single_color_swatch_image.loc[single_color_swatch_image['size_text'].str.contains('Color:', na=False), 'size_text'] = None

In [117]:
# Apply to dataframe
df_parsed = single_color_swatch_image.copy()
df_parsed[['value', 'unit', 'status']] = single_color_swatch_image['size_text'].apply(
    lambda x: pd.Series(parse_size(x))
)

In [118]:
# Analyze results
print("\n=== Status Summary ===")
df_parsed['status'].value_counts()

=== Status Summary ===

status
ok         1155
missing     208
Name: count, dtype: int64

In [119]:
print("\n=== Units (Valid Only) ===")
valid = df_parsed[df_parsed['status'] == 'ok']
valid['unit'].value_counts()

=== Units (Valid Only) ===

unit
oz    1152
ct       3
Name: count, dtype: int64

In [120]:
print("\n=== Errors ===")
errors = df_parsed[df_parsed['status'] != 'ok']
errors[['size_text', 'status']]

=== Errors ===

     size_text   status
25         NaN  missing
26         NaN  missing
27         NaN  missing
55         NaN  missing
119        NaN  missing
...        ...      ...
1360       NaN  missing
1361       NaN  missing
1362       NaN  missing
1363       NaN  missing
1364       NaN  missing

[208 rows x 2 columns]

In [121]:
mask = df_parsed["product_id"].eq("mkt77008719") # has ct as unit

## Modfify 
df_parsed.loc[
    mask,
     ["size_text", "value", "unit", "status"],
] = ["0.14 oz", 0.14, "oz", "ok"]

## verify
df_parsed.loc[
    mask,
    ["product_id", "sku_id", "size_text", "value", "unit", "status"],
]

       product_id    sku_id size_text  value unit status
1322  mkt77008719  77013774   0.14 oz   0.14   oz     ok
1323  mkt77008719  77013772   0.14 oz   0.14   oz     ok
1324  mkt77008719  77013771   0.14 oz   0.14   oz     ok

### Fill in Missing `size_text`

- Merge `product_name` into the a dataframe
- create a reverse lookup from `SIZE_MAP_METRIC`
- Filter and fill missing `size_text`
- Clean up

In [122]:
df_parsed = df_parsed.merge(
    products[['product_id', 'product_name']].drop_duplicates(), # avoid create duplicated rows since `product_id`` appears multiple times in `single_color_swatch_image`
    on = 'product_id', # merge on `product_id`
    how='left', # left join (single_color_swatch_image)
    validate='many_to_one' 
)
df_parsed

,product_id,sku_id,variant_name,variant_description,variant_url,list_price,sale_price,size_text,swatch_image_url,variant_image_url,ingredient_set_id,value,unit,status,product_name
0,pimprod2055883,2647881,Happy,cool pink (dewy),https://www.ulta.com/p/soft-pinch-liquid-blush...,25.0,NaN,0.25 oz,https://media.ultainc.com/i/ulta/2647881_sw?im...,https://media.ultainc.com/i/ulta/2647881?w=500...,dcf984edd911eb352ae36c53c9d9336a74ecf620c5ee8a...,0.25,oz,ok,Soft Pinch Liquid Blush
1,pimprod2055883,2647882,Hope,nude mauve (dewy),https://www.ulta.com/p/soft-pinch-liquid-blush...,25.0,NaN,0.25 oz,https://media.ultainc.com/i/ulta/2647882_sw?im...,https://media.ultainc.com/i/ulta/2647882?w=500...,81cca0463ccff2929af1d5eedc7bcf8bd7546a8fd52acd...,0.25,oz,ok,Soft Pinch Liquid Blush
2,pimprod2055883,2647880,Grateful,true red (dewy),https://www.ulta.com/p/soft-pinch-liquid-blush...,25.0,NaN,0.25 oz,https://media.ultainc.com/i/ulta/2647880_sw?im...,https://media.ultainc.com/i/ulta/2647880?w=500...,dcf984edd911eb352ae36c53c9d9336a74ecf620c5ee8a...,0.25,oz,ok,Soft Pinch Liquid Blush
3,pimprod2055883,2647883,Joy,muted peach (dewy),https://www.ulta.com/p/soft-pinch-liquid-blush...,25.0,NaN,0.25 oz,https://media.ultainc.com/i/ulta/2647883_sw?im...,https://media.ultainc.com/i/ulta/2647883?w=500...,dcf984edd911eb352ae36c53c9d9336a74ecf620c5ee8a...,0.25,oz,ok,Soft Pinch Liquid Blush
4,pimprod2055883,2647884,Lucky,hot pink (dewy),https://www.ulta.com/p/soft-pinch-liquid-blush...,25.0,NaN,0.25 oz,https://media.ultainc.com/i/ulta/2647884_sw?im...,https://media.ultainc.com/i/ulta/2647884?w=500...,dcf984edd911eb352ae36c53c9d9336a74ecf620c5ee8a...,0.25,oz,ok,Soft Pinch Liquid Blush
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,mkt77009883,77015425,Tiramisu,rich cinnamon,https://www.ulta.com/p/vividluxe-creme-blush-s...,48.0,NaN,NaN,https://media.ultainc.com/i/ulta/77015425_sw?i...,https://media.ultainc.com/i/ulta/77015425?w=50...,983b02eae1bab7dc1a1b43504cda4e096f8ec8b0928fd5...,NaN,NaN,missing,VividLuxe Crème Blush Stick
1359,mkt77009884,77015422,Sugar Plum,soft rosy coral with shimmer,https://www.ulta.com/p/pressed-mineral-blush-m...,30.0,NaN,NaN,https://media.ultainc.com/i/ulta/77015422_sw?i...,https://media.ultainc.com/i/ulta/77015422?w=50...,0c9333186d08b09ef8d804ea034f67916b8c2a8f8a2ba1...,NaN,NaN,missing,Pressed Mineral Blush
1360,mkt77009884,77015419,Blossom,soft matte pink,https://www.ulta.com/p/pressed-mineral-blush-m...,30.0,NaN,NaN,https://media.ultainc.com/i/ulta/77015419_sw?i...,https://media.ultainc.com/i/ulta/77015419?w=50...,0c9333186d08b09ef8d804ea034f67916b8c2a8f8a2ba1...,NaN,NaN,missing,Pressed Mineral Blush
1361,mkt77009884,77015427,Nectar,soft peach,https://www.ulta.com/p/pressed-mineral-blush-m...,30.0,NaN,NaN,https://media.ultainc.com/i/ulta/77015427_sw?i...,https://media.ultainc.com/i/ulta/77015427?w=50...,0c9333186d08b09ef8d804ea034f67916b8c2a8f8a2ba1...,NaN,NaN,missing,Pressed Mineral Blush
1362,mkt77009884,77015406,Tangier,shimmering coral,https://www.ulta.com/p/pressed-mineral-blush-m...,30.0,NaN,NaN,https://media.ultainc.com/i/ulta/77015406_sw?i...,https://media.ultainc.com/i/ulta/77015406?w=50...,0c9333186d08b09ef8d804ea034f67916b8c2a8f8a2ba1...,NaN,NaN,missing,Pressed Mineral Blush

In [147]:
## Invert the dict to lookup size_text by product_name
product_to_size = {}
for size, product_names in SIZE_MAP_OZ.items():
    for product_name in product_names:
        product_to_size[product_name] = size

product_to_size

{'Glimmer Super Balm': '0.8 oz',
 'Marble Cream Blush Stick': '0.8 oz',
 'Ultimate Blush Palette': '0.7 oz',
 'Blushed Duo': '0.6 oz',
 'Blursh Pod Domed Blusher': '0.4 oz',
 'MegaGlo Blushlighter': '0.4 oz',
 'VividLuxe Crème Blush Stick': '0.3 oz',
 'DreamStick Cream Blush': '0.3 oz',
 'Cream Stick Blush with Brush Applicator': '0.3 oz',
 'Blush Crush Liquid Blush': '0.3 oz',
 'Effervescence Extra Dimension Face Compact': '0.3 oz',
 'Juice Stick Dewy Gel-Cream Blush': '0.3 oz',
 'Juice Stick Dewy Gel Blush': '0.3 oz',
 'Juice Stick Dewy Sheer Gel Blush': '0.3 oz',
 'Blushed Liquid Blushlighter': '0.3 oz',
 'Glow Time Blush Stick': '0.3 oz',
 'Teint Idole Shape Stick Creamy Blush Stick': '0.3 oz',
 'Unreal Liquid Blush': '0.3 oz',
 'Futurist Blushmaker Dewy Cheek Tint Liquid Blush': '0.3 oz',
 'Superdewy Liquid Blush Burst': '0.3 oz',
 'Juicy Tubes Cheeks Jelly Blush Tint': '0.3 oz',
 'Glimmer Blush Drops': '0.3 oz',
 'Skin Idôle Juicy Liquid Blush': '0.3 oz',
 'Maneater Satin Blush Cheek Plump': '0.3 oz',
 "Simpsons Collab Saucy Sisters' Fat Cheeks Juicy Liquid Blush - Snarky Scarlet": '0.3 oz',
 "Simpsons Collab Saucy Sisters' Fat Cheeks Juicy Liquid Blush - Lavender Sass": '0.3 oz',
 'Macaron Blush & Glow Duo': '0.3 oz',
 'Blushed Cream Blush': '0.2 oz',
 'Matte Blush': '0.2 oz',
 'Megaglo Makeup Stick': '0.2 oz',
 "I'm Blushing 2-in-1 Cheek and Lip Tint": '0.2 oz',
 'Heart Pressed Powder Blush': '0.2 oz',
 'Bouncy Pudding Lip & Cheek Tint': '0.2 oz',
 'Backstage Rosy Glow Stick Radiance and pH-Activated Color Blush Stick': '0.2 oz',
 'Blusher Reloaded': '0.2 oz',
 'Jelly Blush Stick Lip & Cheek Stain': '0.2 oz',
 'Baby Got Blush': '0.2 oz',
 'Bouncy Blur Blush': '0.2 oz',
 '2-in-1 Mosaic Blush & Bronzer Powder': '0.2 oz',
 'Liquid Blush - 2-in-1 Lip & Cheek Tint': '0.2 oz',
 'Strawberry Rococo Series Embossed Blush': '0.2 oz',
 'Blush-Mallow Soft Blusher': '0.2 oz',
 'Skin Silk Marble Blush Stick': '0.2 oz',
 'Mini VividLuxe Crème Blush Stick': '0.2 oz',
 'Play Daze Airy Liquid Blush': '0.2 oz',
 'Play Daze Airy Soft Matte Liquid Blush': '0.2 oz',
 'Convertible Color Lip & Cheek Cream Blush': '0.1 oz',
 'Color Source Buildable Blush': '0.1 oz',
 'Re-tint Blurring Cream Blush': '0.1 oz',
 'PurePressed Blush': '0.1 oz',
 'Magic Touch Cream Blush & Lip Trio': '0.1 oz',
 'Just Kissed Lip and Cheek Stain': '0.1 oz',
 'Pressed Mineral Blush': '0.1 oz',
 'Baked Blush': '0.1 oz',
 'Jelly Tint - 2-in-1 Lip & Cheek Tint Stain': '0.1 oz',
 'Blush Rush Liquid Blush': '0.1 oz',
 'Hot Shot Blush Drops': '0.5 oz',
 'Tinted Moisturizer Cream Blush': '0.5 oz'}

In [148]:
## Filter and fill missing size_text
## Only update rows where size_text is missing AND the product_name exists 

# Create a mask for rows that need update
mask = (
    df_parsed['size_text'].isna() # `size_text` is missing
    &
    df_parsed['product_name'].isin(product_to_size) # `product_name` exists in `product_to_size`
)

df_parsed.loc[mask, 'size_text'] = df_parsed.loc[mask, 'product_name'].map(product_to_size)

In [125]:
df_parsed

,product_id,sku_id,variant_name,variant_description,variant_url,list_price,sale_price,size_text,swatch_image_url,variant_image_url,ingredient_set_id,value,unit,status,product_name
0,pimprod2055883,2647881,Happy,cool pink (dewy),https://www.ulta.com/p/soft-pinch-liquid-blush...,25.0,NaN,0.25 oz,https://media.ultainc.com/i/ulta/2647881_sw?im...,https://media.ultainc.com/i/ulta/2647881?w=500...,dcf984edd911eb352ae36c53c9d9336a74ecf620c5ee8a...,0.25,oz,ok,Soft Pinch Liquid Blush
1,pimprod2055883,2647882,Hope,nude mauve (dewy),https://www.ulta.com/p/soft-pinch-liquid-blush...,25.0,NaN,0.25 oz,https://media.ultainc.com/i/ulta/2647882_sw?im...,https://media.ultainc.com/i/ulta/2647882?w=500...,81cca0463ccff2929af1d5eedc7bcf8bd7546a8fd52acd...,0.25,oz,ok,Soft Pinch Liquid Blush
2,pimprod2055883,2647880,Grateful,true red (dewy),https://www.ulta.com/p/soft-pinch-liquid-blush...,25.0,NaN,0.25 oz,https://media.ultainc.com/i/ulta/2647880_sw?im...,https://media.ultainc.com/i/ulta/2647880?w=500...,dcf984edd911eb352ae36c53c9d9336a74ecf620c5ee8a...,0.25,oz,ok,Soft Pinch Liquid Blush
3,pimprod2055883,2647883,Joy,muted peach (dewy),https://www.ulta.com/p/soft-pinch-liquid-blush...,25.0,NaN,0.25 oz,https://media.ultainc.com/i/ulta/2647883_sw?im...,https://media.ultainc.com/i/ulta/2647883?w=500...,dcf984edd911eb352ae36c53c9d9336a74ecf620c5ee8a...,0.25,oz,ok,Soft Pinch Liquid Blush
4,pimprod2055883,2647884,Lucky,hot pink (dewy),https://www.ulta.com/p/soft-pinch-liquid-blush...,25.0,NaN,0.25 oz,https://media.ultainc.com/i/ulta/2647884_sw?im...,https://media.ultainc.com/i/ulta/2647884?w=500...,dcf984edd911eb352ae36c53c9d9336a74ecf620c5ee8a...,0.25,oz,ok,Soft Pinch Liquid Blush
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,mkt77009883,77015425,Tiramisu,rich cinnamon,https://www.ulta.com/p/vividluxe-creme-blush-s...,48.0,NaN,NaN,https://media.ultainc.com/i/ulta/77015425_sw?i...,https://media.ultainc.com/i/ulta/77015425?w=50...,983b02eae1bab7dc1a1b43504cda4e096f8ec8b0928fd5...,NaN,NaN,missing,VividLuxe Crème Blush Stick
1359,mkt77009884,77015422,Sugar Plum,soft rosy coral with shimmer,https://www.ulta.com/p/pressed-mineral-blush-m...,30.0,NaN,0.11 oz,https://media.ultainc.com/i/ulta/77015422_sw?i...,https://media.ultainc.com/i/ulta/77015422?w=50...,0c9333186d08b09ef8d804ea034f67916b8c2a8f8a2ba1...,NaN,NaN,missing,Pressed Mineral Blush
1360,mkt77009884,77015419,Blossom,soft matte pink,https://www.ulta.com/p/pressed-mineral-blush-m...,30.0,NaN,0.11 oz,https://media.ultainc.com/i/ulta/77015419_sw?i...,https://media.ultainc.com/i/ulta/77015419?w=50...,0c9333186d08b09ef8d804ea034f67916b8c2a8f8a2ba1...,NaN,NaN,missing,Pressed Mineral Blush
1361,mkt77009884,77015427,Nectar,soft peach,https://www.ulta.com/p/pressed-mineral-blush-m...,30.0,NaN,0.11 oz,https://media.ultainc.com/i/ulta/77015427_sw?i...,https://media.ultainc.com/i/ulta/77015427?w=50...,0c9333186d08b09ef8d804ea034f67916b8c2a8f8a2ba1...,NaN,NaN,missing,Pressed Mineral Blush
1362,mkt77009884,77015406,Tangier,shimmering coral,https://www.ulta.com/p/pressed-mineral-blush-m...,30.0,NaN,0.11 oz,https://media.ultainc.com/i/ulta/77015406_sw?i...,https://media.ultainc.com/i/ulta/77015406?w=50...,0c9333186d08b09ef8d804ea034f67916b8c2a8f8a2ba1...,NaN,NaN,missing,Pressed Mineral Blush

In [149]:
df3 = df_parsed.loc[df_parsed['size_text'].isna(),['product_id', 'product_name', "size_text"]].drop_duplicates(subset=['product_id']) # df3 now only has missing size_text with unique product_id
df3

,product_id,product_name,size_text
55,pimprod2044741,Blush,NaN
119,pimprod2050543,Cooling Water Jelly Tint Lip + Cheek Blush Stain,NaN
175,xlsImpprod15921186,Mineralize Powder Blush,NaN
294,pimprod2049596,GEN NUDE Powder Blush,NaN
322,pimprod2043819,Value Size Liquid Lip Blush & Cheek Tint,NaN
556,pimprod2049564,JOUES CONTRASTE Powder Blush,NaN
1025,pimprod2046332,Twist Tint Color Shifting Lip & Cheek Stick,NaN
1126,pimprod2056852,pH Cheeky Glaze Liquid Blush,NaN
1215,pimprod2052046,+Rose Glow-y Powder,NaN
1224,pimprod2045569,Cream to Powder Blurring Blush Stick,NaN
1225,xlsImpprod16731045,MegaGlo Makeup Stick Blush,NaN
1232,pimprod2047580,Cheek Kiss Liquid Blush + Glow,NaN
1233,pimprod2045404,Bright Light Blush Drops,NaN
1234,pimprod2024993,Superdewy Liquid Blush,NaN
1235,pimprod2030849,Soft Matte Cream Blush,NaN
1236,pimprod2027378,Sheer Cheek Gel,NaN
1237,pimprod2049311,Beam Bright Blush,NaN
1244,pimprod2038007,Puff Paint Liquid Blush,NaN

In [150]:
df2 = pd.read_csv(r"C:\Users\Thao\Desktop\Github\Ulta_Project\data\raw\ulta_blush.csv", encoding='utf-8-sig')
df2

,shade_url,brand,product_name,shade,swatch_img_url,swatch_alt,description,price,currency,size
0,https://www.ulta.com/p/trublend-skin-enhancer-...,CoverGirl,Trublend Skin Enhancer Balm Blush Stick,Bubblegum Pop,https://media.ultainc.com/i/ulta/2634527_sw?im...,Bubblegum Pop Trublend Skin Enhancer Balm Blus...,"cool, bright pink",12.99,USD,0.21 oz
1,https://www.ulta.com/p/trublend-skin-enhancer-...,CoverGirl,Trublend Skin Enhancer Balm Blush Stick,Candied Strawberry,https://media.ultainc.com/i/ulta/2652760_sw?im...,Candied Strawberry Trublend Skin Enhancer Balm...,bright red,12.99,USD,0.21 oz
2,https://www.ulta.com/p/trublend-skin-enhancer-...,CoverGirl,Trublend Skin Enhancer Balm Blush Stick,Midnight Plum,https://media.ultainc.com/i/ulta/2652756_sw?im...,Midnight Plum Trublend Skin Enhancer Balm Blus...,deep berry,12.99,USD,0.21 oz
3,https://www.ulta.com/p/trublend-skin-enhancer-...,CoverGirl,Trublend Skin Enhancer Balm Blush Stick,Nude Flush,https://media.ultainc.com/i/ulta/2634526_sw?im...,Nude Flush Trublend Skin Enhancer Balm Blush S...,nude pink,12.99,USD,0.21 oz
4,https://www.ulta.com/p/trublend-skin-enhancer-...,CoverGirl,Trublend Skin Enhancer Balm Blush Stick,Pink Sprinkle,https://media.ultainc.com/i/ulta/2652758_sw?im...,Pink Sprinkle Trublend Skin Enhancer Balm Blus...,warm pink,12.99,USD,0.21 oz
...,...,...,...,...,...,...,...,...,...,...
1509,https://www.ulta.com/p/everlasting-refillable-...,KVD Beauty,Everlasting Refillable Blush,Snapdragon,https://media.ultainc.com/i/ulta/2571833_sw?im...,Snapdragon Everlasting Refillable Blush,coco crimson,29.50,USD,0.22 oz
1510,https://www.ulta.com/p/clean-fresh-all-over-de...,CoverGirl,Clean Fresh All Over Dewy Tint,Fuchsia Passion,https://media.ultainc.com/i/ulta/2597351_sw?im...,Fuchsia Passion Clean Fresh All Over Dewy Tint,NaN,5.49,USD,0.33 oz
1511,https://www.ulta.com/p/clean-fresh-all-over-de...,CoverGirl,Clean Fresh All Over Dewy Tint,Mauvy Kiss,https://media.ultainc.com/i/ulta/2597354_sw?im...,Mauvy Kiss Clean Fresh All Over Dewy Tint,NaN,5.49,USD,0.33 oz
1512,https://www.ulta.com/p/clean-fresh-all-over-de...,CoverGirl,Clean Fresh All Over Dewy Tint,Dreamy Pink,https://media.ultainc.com/i/ulta/2597355_sw?im...,Dreamy Pink Clean Fresh All Over Dewy Tint,NaN,5.49,USD,0.33 oz
1513,https://www.ulta.com/p/clean-fresh-all-over-de...,CoverGirl,Clean Fresh All Over Dewy Tint,Cozy Coral,https://media.ultainc.com/i/ulta/2597356_sw?im...,Cozy Coral Clean Fresh All Over Dewy Tint,NaN,5.49,USD,0.33 oz

In [151]:
# Get missing product_ids
missing_ids = df3['product_name'].unique()
missing_ids

<StringArray>
[                                           'Blush',
 'Cooling Water Jelly Tint Lip + Cheek Blush Stain',
                          'Mineralize Powder Blush',
                            'GEN NUDE Powder Blush',
         'Value Size Liquid Lip Blush & Cheek Tint',
                     'JOUES CONTRASTE Powder Blush',
      'Twist Tint Color Shifting Lip & Cheek Stick',
                     'pH Cheeky Glaze Liquid Blush',
                              '+Rose Glow-y Powder',
             'Cream to Powder Blurring Blush Stick',
                       'MegaGlo Makeup Stick Blush',
                   'Cheek Kiss Liquid Blush + Glow',
                         'Bright Light Blush Drops',
                           'Superdewy Liquid Blush',
                           'Soft Matte Cream Blush',
                                  'Sheer Cheek Gel',
                                'Beam Bright Blush',
                          'Puff Paint Liquid Blush']
Length: 18, dtype: str

In [152]:
def find_size(product_id):
    matching_sizes = (
        df2.loc[
            df2["shade_url"].astype("string").str.contains(
                str(product_id),
                regex=False,
                na=False,
            ),
            "size",
        ]
        .dropna()
        .astype(str)
        .str.strip()
    )

    matching_sizes = matching_sizes[matching_sizes.ne("")]

    if matching_sizes.empty:
        return pd.NA

    return matching_sizes.iloc[0]


df3["size_text"] = df3["product_id"].map(find_size)

In [154]:
df3.loc[mask, 'size_text'] = df3.loc[mask, 'product_name'].map(product_to_size)

In [156]:
## conditions: df_parsed['product_id'] == df3['product_id'] & df3['size_text'] != None

## Step 1: Create a lookup dictionary from df3
### This dict maps product_id to size_text (skipping NaN values)
lookup = df3.set_index('product_id')['size_text'].dropna().to_dict() # using product_id as the key, size_text as the value

## Step 2: Use map() to fill missing values (.fillna()) in df_parsed
df_parsed['size_text'] = df_parsed['size_text'].fillna(df_parsed['product_id'].map(lookup))

In [161]:
df_parsed[df_parsed['size_text'].isna()]

Empty DataFrame
Columns: [product_id, sku_id, variant_name, variant_description, variant_url, list_price, sale_price, size_text, swatch_image_url, variant_image_url, ingredient_set_id, value, unit, status, product_name]
Index: []

In [ ]:
# df_parsed.loc[df_parsed['size_text'].isna(),['product_id', 'product_name', "size_text", "variant_url"]]#.drop_duplicates(subset=['product_id']) # display

,product_id,product_name,size_text,variant_url
496,pimprod2043833,Blushed Liquid Blushlighter,NaN,https://www.ulta.com/p/blushed-liquid-blushlig...
497,pimprod2043833,Blushed Liquid Blushlighter,NaN,https://www.ulta.com/p/blushed-liquid-blushlig...
498,pimprod2043833,Blushed Liquid Blushlighter,NaN,https://www.ulta.com/p/blushed-liquid-blushlig...
499,pimprod2043833,Blushed Liquid Blushlighter,NaN,https://www.ulta.com/p/blushed-liquid-blushlig...
500,pimprod2043833,Blushed Liquid Blushlighter,NaN,https://www.ulta.com/p/blushed-liquid-blushlig...
501,pimprod2043833,Blushed Liquid Blushlighter,NaN,https://www.ulta.com/p/blushed-liquid-blushlig...
502,pimprod2043833,Blushed Liquid Blushlighter,NaN,https://www.ulta.com/p/blushed-liquid-blushlig...
509,pimprod2057553,Juice Stick Dewy Sheer Gel Blush,NaN,https://www.ulta.com/p/juice-stick-dewy-sheer-...
510,pimprod2057553,Juice Stick Dewy Sheer Gel Blush,NaN,https://www.ulta.com/p/juice-stick-dewy-sheer-...
511,pimprod2057553,Juice Stick Dewy Sheer Gel Blush,NaN,https://www.ulta.com/p/juice-stick-dewy-sheer-...
512,pimprod2057553,Juice Stick Dewy Sheer Gel Blush,NaN,https://www.ulta.com/p/juice-stick-dewy-sheer-...
513,pimprod2057553,Juice Stick Dewy Sheer Gel Blush,NaN,https://www.ulta.com/p/juice-stick-dewy-sheer-...
801,pimprod2046549,Blush Crush Liquid Blush,NaN,https://www.ulta.com/p/blush-crush-liquid-blus...
802,pimprod2046549,Blush Crush Liquid Blush,NaN,https://www.ulta.com/p/blush-crush-liquid-blus...
803,pimprod2046549,Blush Crush Liquid Blush,NaN,https://www.ulta.com/p/blush-crush-liquid-blus...
804,pimprod2046549,Blush Crush Liquid Blush,NaN,https://www.ulta.com/p/blush-crush-liquid-blus...
805,pimprod2046549,Blush Crush Liquid Blush,NaN,https://www.ulta.com/p/blush-crush-liquid-blus...
1117,pimprod2032200,PurePressed Blush,NaN,https://www.ulta.com/p/purepressed-blush-pimpr...
1223,pimprod2013408,MegaGlo Blushlighter,NaN,https://www.ulta.com/p/megaglo-blushlighter-pi...
1339,mkt77009882,Mini VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/mini-vividluxe-creme-bl...
1340,mkt77009882,Mini VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/mini-vividluxe-creme-bl...
1341,mkt77009882,Mini VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/mini-vividluxe-creme-bl...
1342,mkt77009882,Mini VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/mini-vividluxe-creme-bl...
1343,mkt77009882,Mini VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/mini-vividluxe-creme-bl...
1344,mkt77009882,Mini VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/mini-vividluxe-creme-bl...
1345,mkt77009882,Mini VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/mini-vividluxe-creme-bl...
1346,mkt77009882,Mini VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/mini-vividluxe-creme-bl...
1347,mkt77009882,Mini VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/mini-vividluxe-creme-bl...
1348,mkt77009882,Mini VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/mini-vividluxe-creme-bl...
1349,mkt77009883,VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/vividluxe-creme-blush-s...
1350,mkt77009883,VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/vividluxe-creme-blush-s...
1351,mkt77009883,VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/vividluxe-creme-blush-s...
1352,mkt77009883,VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/vividluxe-creme-blush-s...
1353,mkt77009883,VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/vividluxe-creme-blush-s...
1354,mkt77009883,VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/vividluxe-creme-blush-s...
1355,mkt77009883,VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/vividluxe-creme-blush-s...
1356,mkt77009883,VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/vividluxe-creme-blush-s...
1357,mkt77009883,VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/vividluxe-creme-blush-s...
1358,mkt77009883,VividLuxe Crème Blush Stick,NaN,https://www.ulta.com/p/vividluxe-creme-blush-s...

In [170]:
DUPLICATE_UNIT_PATTERN = re.compile(
    r"\b([a-zA-Z]+)\.?\s+\1\.?\s*$",
    flags=re.IGNORECASE,
)

def parse_size(size_text):
    if pd.isna(size_text):
        return None, None

    cleaned_text = str(size_text).strip()

    cleaned_text = DUPLICATE_UNIT_PATTERN.sub(
        lambda match: match.group(1).lower(),
        cleaned_text
    )

    match = re.fullmatch(
        r"\s*(\d*\.?\d+)\s*(.*?)\s*",
        cleaned_text,
    )

    if not match:
        return None, None

    value = float(match.group(1))
    unit = match.group(2).strip()

    return cleaned_text, value, unit

In [171]:
df_parse = df_parsed.drop(columns='status')
df_parse[["size_text", "value", "unit"]] = (
    df_parsed["size_text"]
    .apply(parse_size)
    .apply(pd.Series)
)

## Export Files

In [172]:
import os

output_dir = "../data/processed_data/test/blushes/cleaned"
os.makedirs(output_dir, exist_ok=True)

In [173]:
# # Export to CSV
df_parse.to_csv(f"{output_dir}/cleaned_single_blush.csv", encoding='utf-8-sig', index=False)

thank you for the `parse_size()` but you're missing out a part, I think it's because i'm not clear enough. I want to reorganized the cleaning logic of handling both missing and incorrect values of `size_text`. how about we create functions each handling an issue of 'size_text', then have a main function, to call these function in an order that logical and efficienly fix these problems?